<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20231122162745 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('DROP SEQUENCE benlalam.lecteur_id_seq CASCADE');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE benahamadi.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE benahamadi.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE praizelin.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE tschaen.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE tillocher.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE tillocher.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE praizelin.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE praizelin.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE barbotteau.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE praizelin.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE praizelin.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE tillocher.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE tillocher.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE tillocher.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE benahamadi.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE benahamadi.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE benahamadi.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE koudjowa.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE koudjowa.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE taurand.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE taurand.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE denieul.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE marie.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE marie.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE taurand.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE taurand.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE denieul.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE denieul.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE denieul.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE denieul.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE marie.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE marie.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE taurand.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE marie.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE koudjowa.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE koudjowa.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE koudjowa.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE barbotteau.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE barbotteau.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE pencole.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE pencole.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE pencole.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE pencole.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE pencole.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE perreux.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE mousnier.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE mousnier.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE mousnier.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE mousnier.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE perreux.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE perreux.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE tschaen.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE tschaen.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE perreux.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE perreux.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('ALTER TABLE tschaen.appartenir DROP CONSTRAINT appartenir_fk');
        $this->addSql('ALTER TABLE tschaen.appartenir DROP CONSTRAINT appartenir_fk_1');
        $this->addSql('ALTER TABLE mousnier.livre DROP CONSTRAINT livre_fk');
        $this->addSql('ALTER TABLE barbotteau.exemplaire DROP CONSTRAINT exemplaire_fk');
        $this->addSql('ALTER TABLE barbotteau.exemplaire DROP CONSTRAINT exemplaire_fk_1');
        $this->addSql('DROP TABLE praizelin.genre');
        $this->addSql('DROP TABLE barbotteau.auteur');
        $this->addSql('DROP TABLE praizelin.auteur');
        $this->addSql('DROP TABLE pencole.admin');
        $this->addSql('DROP TABLE barbotteau.admin');
        $this->addSql('DROP TABLE benahamadi.exemplaire');
        $this->addSql('DROP TABLE praizelin.livre');
        $this->addSql('DROP TABLE tschaen.livre');
        $this->addSql('DROP TABLE perreux.admin');
        $this->addSql('DROP TABLE tillocher.lecteur');
        $this->addSql('DROP TABLE tillocher.exemplaire');
        $this->addSql('DROP TABLE praizelin.appartenir');
        $this->addSql('DROP TABLE barbotteau.livre');
        $this->addSql('DROP TABLE praizelin.exemplaire');
        $this->addSql('DROP TABLE tillocher.appartenir');
        $this->addSql('DROP TABLE tillocher.genre');
        $this->addSql('DROP TABLE praizelin.lecteur');
        $this->addSql('DROP TABLE taurand.lecteur');
        $this->addSql('DROP TABLE tillocher.livre');
        $this->addSql('DROP TABLE tillocher.auteur');
        $this->addSql('DROP TABLE koudjowa.admin');
        $this->addSql('DROP TABLE mousnier.admin');
        $this->addSql('DROP TABLE tschaen.auteur');
        $this->addSql('DROP TABLE benahamadi.lecteur');
        $this->addSql('DROP TABLE praizelin.admin');
        $this->addSql('DROP TABLE benahamadi.appartenir');
        $this->addSql('DROP TABLE benahamadi.genre');
        $this->addSql('DROP TABLE benahamadi.auteur');
        $this->addSql('DROP TABLE denieul.genre');
        $this->addSql('DROP TABLE benahamadi.livre');
        $this->addSql('DROP TABLE marie.genre');
        $this->addSql('DROP TABLE denieul.auteur');
        $this->addSql('DROP TABLE tschaen."user"');
        $this->addSql('DROP TABLE koudjowa.exemplaire');
        $this->addSql('DROP TABLE taurand.exemplaire');
        $this->addSql('DROP TABLE denieul.livre');
        $this->addSql('DROP TABLE marie.appartenir');
        $this->addSql('DROP TABLE koudjowa.lecteur');
        $this->addSql('DROP TABLE taurand.appartenir');
        $this->addSql('DROP TABLE marie.auteur');
        $this->addSql('DROP TABLE denieul.appartenir');
        $this->addSql('DROP TABLE lecteur');
        $this->addSql('DROP TABLE denieul.exemplaire');
        $this->addSql('DROP TABLE marie.exemplaire');
        $this->addSql('DROP TABLE taurand.livre');
        $this->addSql('DROP TABLE taurand.auteur');
        $this->addSql('DROP TABLE denieul.lecteur');
        $this->addSql('DROP TABLE marie.livre');
        $this->addSql('DROP TABLE taurand.genre');
        $this->addSql('DROP TABLE koudjowa.appartenir');
        $this->addSql('DROP TABLE koudjowa.livre');
        $this->addSql('DROP TABLE koudjowa.auteur');
        $this->addSql('DROP TABLE barbotteau.appartenir');
        $this->addSql('DROP TABLE barbotteau.lecteur');
        $this->addSql('DROP TABLE koudjowa.genre');
        $this->addSql('DROP TABLE tillocher.admin');
        $this->addSql('DROP TABLE barbotteau.messenger_messages');
        $this->addSql('DROP TABLE perreux.lecteur');
        $this->addSql('DROP TABLE marie.lecteur');
        $this->addSql('DROP TABLE pencole.lecteur');
        $this->addSql('DROP TABLE pencole.exemplaire');
        $this->addSql('DROP TABLE pencole.appartenir');
        $this->addSql('DROP TABLE pencole.genre');
        $this->addSql('DROP TABLE perreux.auteur');
        $this->addSql('DROP TABLE denieul.Admin');
        $this->addSql('DROP TABLE pencole.livre');
        $this->addSql('DROP TABLE pencole.auteur');
        $this->addSql('DROP TABLE marie.admin');
        $this->addSql('DROP TABLE perreux.livre');
        $this->addSql('DROP TABLE mousnier.lecteur');
        $this->addSql('DROP TABLE mousnier.exemplaire');
        $this->addSql('DROP TABLE mousnier.appartenir');
        $this->addSql('DROP TABLE perreux.genre');
        $this->addSql('DROP TABLE tschaen.lecteur');
        $this->addSql('DROP TABLE perreux.appartenir');
        $this->addSql('DROP TABLE tschaen.exemplaire');
        $this->addSql('DROP TABLE perreux.exemplaire');
        $this->addSql('DROP TABLE tschaen.appartenir');
        $this->addSql('DROP TABLE mousnier.genre');
        $this->addSql('DROP TABLE mousnier.livre');
        $this->addSql('DROP TABLE barbotteau.exemplaire');
        $this->addSql('DROP TABLE barbotteau.genre');
        $this->addSql('DROP TABLE mousnier.auteur');
        $this->addSql('DROP TABLE tschaen.genre');
        $this->addSql('DROP TABLE benahamadi.admin');
        $this->addSql('ALTER TABLE admin ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE admin ALTER username TYPE VARCHAR(180)');
        $this->addSql('ALTER TABLE admin ALTER roles TYPE JSON');
        $this->addSql('ALTER TABLE admin ALTER password TYPE VARCHAR(255)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_880E0D76F85E0677 ON admin (username)');
        $this->addSql('ALTER TABLE auteur DROP datedenaissance');
        $this->addSql('ALTER TABLE auteur DROP datededeces');
        $this->addSql('ALTER TABLE auteur ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE auteur ALTER nom SET NOT NULL');
        $this->addSql('ALTER TABLE auteur ALTER prenom SET NOT NULL');
        $this->addSql('DROP INDEX IDX_5EF83C92952067DE');
        $this->addSql('ALTER TABLE exemplaire DROP emprunteur');
        $this->addSql('ALTER TABLE exemplaire ALTER dateretour TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE genre ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE genre ALTER libelle SET NOT NULL');
        $this->addSql('ALTER TABLE livre ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE livre ALTER idauteur SET NOT NULL');
        $this->addSql('ALTER TABLE livre ALTER titre SET NOT NULL');
        $this->addSql('ALTER TABLE livre ALTER resume SET NOT NULL');
        $this->addSql('ALTER TABLE livre ALTER isbn TYPE INT');
        $this->addSql('ALTER TABLE livre ALTER isbn SET NOT NULL');
        $this->addSql('ALTER TABLE appartenir DROP CONSTRAINT appartenir_pkey');
        $this->addSql('ALTER TABLE appartenir ADD PRIMARY KEY (idlivre, idgenre)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SCHEMA benlalam');
        $this->addSql('CREATE SCHEMA praizelin');
        $this->addSql('CREATE SCHEMA barbotteau');
        $this->addSql('CREATE SCHEMA pencole');
        $this->addSql('CREATE SCHEMA benahamadi');
        $this->addSql('CREATE SCHEMA perreux');
        $this->addSql('CREATE SCHEMA tschaen');
        $this->addSql('CREATE SCHEMA tillocher');
        $this->addSql('CREATE SCHEMA taurand');
        $this->addSql('CREATE SCHEMA koudjowa');
        $this->addSql('CREATE SCHEMA mousnier');
        $this->addSql('CREATE SCHEMA denieul');
        $this->addSql('CREATE SCHEMA marie');
        $this->addSql('CREATE SEQUENCE benlalam.lecteur_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE praizelin.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE barbotteau.auteur (id INT NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE praizelin.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pencole.admin (id INT DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, roles VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL)');
        $this->addSql('CREATE TABLE barbotteau.admin (id SERIAL NOT NULL, username VARCHAR(255) DEFAULT NULL, roles VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE benahamadi.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_8A1835947A662380 ON benahamadi.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_8A183594952067DE ON benahamadi.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE praizelin.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6ECE1CF861E71CEC ON praizelin.livre (idauteur)');
        $this->addSql('CREATE TABLE tschaen.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7296676B61E71CEC ON tschaen.livre (idauteur)');
        $this->addSql('CREATE TABLE perreux.admin (id SERIAL NOT NULL, username VARCHAR(255) DEFAULT NULL, roles VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, is_verified BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tillocher.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tillocher.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_CFA370237A662380 ON tillocher.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_CFA37023952067DE ON tillocher.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE praizelin.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_F7265C4255555FE1 ON praizelin.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_F7265C427A662380 ON praizelin.appartenir (idlivre)');
        $this->addSql('CREATE TABLE barbotteau.livre (id INT NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) NOT NULL, resume TEXT DEFAULT NULL, isbn VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C4ACD52D61E71CEC ON barbotteau.livre (idauteur)');
        $this->addSql('CREATE TABLE praizelin.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_B7EB9DC7A662380 ON praizelin.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_B7EB9DC952067DE ON praizelin.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE tillocher.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_33FB95BD55555FE1 ON tillocher.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_33FB95BD7A662380 ON tillocher.appartenir (idlivre)');
        $this->addSql('CREATE TABLE tillocher.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE praizelin.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE taurand.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, email VARCHAR(50) DEFAULT NULL, password VARCHAR(100) DEFAULT NULL, roles JSONB DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tillocher.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A35C34361E71CEC ON tillocher.livre (idauteur)');
        $this->addSql('CREATE TABLE tillocher.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE koudjowa.admin (id SERIAL NOT NULL, username VARCHAR(255) DEFAULT NULL, roles VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mousnier.admin (id SERIAL NOT NULL, username VARCHAR(255) DEFAULT NULL, roles VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL)');
        $this->addSql('CREATE TABLE tschaen.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE benahamadi.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE praizelin.admin (id SERIAL NOT NULL, username VARCHAR(25) DEFAULT NULL, roles VARCHAR(50) DEFAULT NULL, password VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE benahamadi.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_7640D00A55555FE1 ON benahamadi.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_7640D00A7A662380 ON benahamadi.appartenir (idlivre)');
        $this->addSql('CREATE TABLE benahamadi.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE benahamadi.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE denieul.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE benahamadi.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7AADF33761E71CEC ON benahamadi.livre (idauteur)');
        $this->addSql('CREATE TABLE marie.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE denieul.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tschaen."user" (id SERIAL NOT NULL, lecteur_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE koudjowa.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_953DEE1C7A662380 ON koudjowa.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_953DEE1C952067DE ON koudjowa.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE taurand.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_FD760A8F7A662380 ON taurand.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_FD760A8F952067DE ON taurand.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE denieul.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B72ADE9A61E71CEC ON denieul.livre (idauteur)');
        $this->addSql('CREATE TABLE marie.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_8023B36D55555FE1 ON marie.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_8023B36D7A662380 ON marie.appartenir (idlivre)');
        $this->addSql('CREATE TABLE koudjowa.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE taurand.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_12EEF1155555FE1 ON taurand.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_12EEF117A662380 ON taurand.appartenir (idlivre)');
        $this->addSql('CREATE TABLE marie.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE denieul.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_368158C855555FE1 ON denieul.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_368158C87A662380 ON denieul.appartenir (idlivre)');
        $this->addSql('CREATE TABLE lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE denieul.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_CAD9BD567A662380 ON denieul.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_CAD9BD56952067DE ON denieul.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE marie.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_7C7B56F37A662380 ON marie.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_7C7B56F3952067DE ON marie.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE taurand.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1D6048B961E71CEC ON taurand.livre (idauteur)');
        $this->addSql('CREATE TABLE taurand.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE denieul.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE marie.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_517AEADE61E71CEC ON marie.livre (idauteur)');
        $this->addSql('CREATE TABLE taurand.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE koudjowa.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_69650B8255555FE1 ON koudjowa.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_69650B827A662380 ON koudjowa.appartenir (idlivre)');
        $this->addSql('CREATE TABLE koudjowa.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FE9508E061E71CEC ON koudjowa.livre (idauteur)');
        $this->addSql('CREATE TABLE koudjowa.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE barbotteau.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_A2CD46CA55555FE1 ON barbotteau.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_A2CD46CA7A662380 ON barbotteau.appartenir (idlivre)');
        $this->addSql('CREATE TABLE barbotteau.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE koudjowa.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tillocher.admin (id INT NOT NULL, username TEXT DEFAULT NULL, password TEXT DEFAULT NULL, roles TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE barbotteau.messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON barbotteau.messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON barbotteau.messenger_messages (available_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON barbotteau.messenger_messages (queue_name)');
        $this->addSql('CREATE TABLE perreux.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE marie.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pencole.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pencole.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_F4D107667A662380 ON pencole.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_F4D10766952067DE ON pencole.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE pencole.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_889E2F855555FE1 ON pencole.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_889E2F87A662380 ON pencole.appartenir (idlivre)');
        $this->addSql('CREATE TABLE pencole.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE perreux.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE denieul.Admin (id SERIAL NOT NULL, username VARCHAR(255) DEFAULT NULL, roles VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pencole.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B7F4675261E71CEC ON pencole.livre (idauteur)');
        $this->addSql('CREATE TABLE pencole.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE marie.admin (id SERIAL NOT NULL, username VARCHAR(255) DEFAULT NULL, roles VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE perreux.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2BA7861861E71CEC ON perreux.livre (idauteur)');
        $this->addSql('CREATE TABLE mousnier.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mousnier.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_CE5C21AC7A662380 ON mousnier.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_CE5C21AC952067DE ON mousnier.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE mousnier.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_3204C43255555FE1 ON mousnier.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_3204C4327A662380 ON mousnier.appartenir (idlivre)');
        $this->addSql('CREATE TABLE perreux.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tschaen.lecteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datepremiereadhesion DATE DEFAULT NULL, datefinadhesion DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE perreux.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_C707D1B255555FE1 ON perreux.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_C707D1B27A662380 ON perreux.appartenir (idlivre)');
        $this->addSql('CREATE TABLE tschaen.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_A53EE1D47A662380 ON tschaen.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_A53EE1D4952067DE ON tschaen.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE perreux.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_3B5F342C7A662380 ON perreux.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_3B5F342C952067DE ON perreux.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE tschaen.appartenir (idlivre INT NOT NULL, idgenre INT NOT NULL, PRIMARY KEY(idgenre, idlivre))');
        $this->addSql('CREATE INDEX IDX_5966044A55555FE1 ON tschaen.appartenir (idgenre)');
        $this->addSql('CREATE INDEX IDX_5966044A7A662380 ON tschaen.appartenir (idlivre)');
        $this->addSql('CREATE TABLE mousnier.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mousnier.livre (id SERIAL NOT NULL, idauteur INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, resume VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_93C3FBEB61E71CEC ON mousnier.livre (idauteur)');
        $this->addSql('CREATE TABLE barbotteau.exemplaire (numero INT NOT NULL, idlivre INT NOT NULL, emprunteur INT DEFAULT NULL, dateretour DATE DEFAULT NULL, PRIMARY KEY(numero, idlivre))');
        $this->addSql('CREATE INDEX IDX_5E95A3547A662380 ON barbotteau.exemplaire (idlivre)');
        $this->addSql('CREATE INDEX IDX_5E95A354952067DE ON barbotteau.exemplaire (emprunteur)');
        $this->addSql('CREATE TABLE barbotteau.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mousnier.auteur (id SERIAL NOT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, datedenaissance DATE DEFAULT NULL, datededeces DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tschaen.genre (id SERIAL NOT NULL, libelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE benahamadi.admin (username VARCHAR(255) DEFAULT NULL, roles VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL)');
        $this->addSql('ALTER TABLE benahamadi.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES benahamadi.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE benahamadi.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES benahamadi.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE praizelin.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES praizelin.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tschaen.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES tschaen.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tillocher.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES tillocher.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tillocher.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES tillocher.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE praizelin.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES praizelin.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE praizelin.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES praizelin.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE barbotteau.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES barbotteau.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE praizelin.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES praizelin.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE praizelin.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES praizelin.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tillocher.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES tillocher.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tillocher.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES tillocher.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tillocher.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES tillocher.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE benahamadi.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES benahamadi.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE benahamadi.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES benahamadi.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE benahamadi.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES benahamadi.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE koudjowa.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES koudjowa.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE koudjowa.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES koudjowa.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE taurand.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES taurand.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE taurand.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES taurand.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denieul.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES denieul.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE marie.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES marie.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE marie.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES marie.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE taurand.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES taurand.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE taurand.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES taurand.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denieul.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES denieul.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denieul.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES denieul.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denieul.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES denieul.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE denieul.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES denieul.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE marie.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES marie.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE marie.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES marie.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE taurand.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES taurand.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE marie.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES marie.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE koudjowa.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES koudjowa.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE koudjowa.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES koudjowa.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE koudjowa.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES koudjowa.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE barbotteau.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES barbotteau.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE barbotteau.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES barbotteau.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pencole.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES pencole.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pencole.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES pencole.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pencole.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES pencole.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pencole.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES pencole.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pencole.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES pencole.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE perreux.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES perreux.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mousnier.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES mousnier.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mousnier.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES mousnier.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mousnier.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES mousnier.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mousnier.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES mousnier.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE perreux.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES perreux.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE perreux.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES perreux.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tschaen.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES tschaen.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tschaen.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES tschaen.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE perreux.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES perreux.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE perreux.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES perreux.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tschaen.appartenir ADD CONSTRAINT appartenir_fk FOREIGN KEY (idgenre) REFERENCES tschaen.genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tschaen.appartenir ADD CONSTRAINT appartenir_fk_1 FOREIGN KEY (idlivre) REFERENCES tschaen.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mousnier.livre ADD CONSTRAINT livre_fk FOREIGN KEY (idauteur) REFERENCES mousnier.auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE barbotteau.exemplaire ADD CONSTRAINT exemplaire_fk FOREIGN KEY (idlivre) REFERENCES barbotteau.livre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE barbotteau.exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES barbotteau.lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP INDEX appartenir_pk');
        $this->addSql('ALTER TABLE appartenir ADD PRIMARY KEY (idgenre, idlivre)');
        $this->addSql('DROP INDEX UNIQ_880E0D76F85E0677');
        $this->addSql('CREATE SEQUENCE admin_id_seq');
        $this->addSql('SELECT setval(\'admin_id_seq\', (SELECT MAX(id) FROM admin))');
        $this->addSql('ALTER TABLE admin ALTER id SET DEFAULT nextval(\'admin_id_seq\')');
        $this->addSql('ALTER TABLE admin ALTER username TYPE TEXT');
        $this->addSql('ALTER TABLE admin ALTER username TYPE TEXT');
        $this->addSql('ALTER TABLE admin ALTER roles TYPE TEXT');
        $this->addSql('ALTER TABLE admin ALTER password TYPE TEXT');
        $this->addSql('CREATE SEQUENCE genre_id_seq');
        $this->addSql('SELECT setval(\'genre_id_seq\', (SELECT MAX(id) FROM genre))');
        $this->addSql('ALTER TABLE genre ALTER id SET DEFAULT nextval(\'genre_id_seq\')');
        $this->addSql('ALTER TABLE genre ALTER libelle DROP NOT NULL');
        $this->addSql('CREATE SEQUENCE livre_id_seq');
        $this->addSql('SELECT setval(\'livre_id_seq\', (SELECT MAX(id) FROM livre))');
        $this->addSql('ALTER TABLE livre ALTER id SET DEFAULT nextval(\'livre_id_seq\')');
        $this->addSql('ALTER TABLE livre ALTER idauteur DROP NOT NULL');
        $this->addSql('ALTER TABLE livre ALTER titre DROP NOT NULL');
        $this->addSql('ALTER TABLE livre ALTER resume DROP NOT NULL');
        $this->addSql('ALTER TABLE livre ALTER isbn TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE livre ALTER isbn DROP NOT NULL');
        $this->addSql('ALTER TABLE auteur ADD datedenaissance DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE auteur ADD datededeces DATE DEFAULT NULL');
        $this->addSql('CREATE SEQUENCE auteur_id_seq');
        $this->addSql('SELECT setval(\'auteur_id_seq\', (SELECT MAX(id) FROM auteur))');
        $this->addSql('ALTER TABLE auteur ALTER id SET DEFAULT nextval(\'auteur_id_seq\')');
        $this->addSql('ALTER TABLE auteur ALTER nom DROP NOT NULL');
        $this->addSql('ALTER TABLE auteur ALTER prenom DROP NOT NULL');
        $this->addSql('ALTER TABLE exemplaire ADD emprunteur INT DEFAULT NULL');
        $this->addSql('ALTER TABLE exemplaire ALTER dateretour TYPE DATE');
        $this->addSql('ALTER TABLE exemplaire ADD CONSTRAINT exemplaire_fk_1 FOREIGN KEY (emprunteur) REFERENCES lecteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_5EF83C92952067DE ON exemplaire (emprunteur)');
    }
}
